export const ROUTES = {
    user:{
        base:'user',
        dashboard:'dashboard',
        goals:'goals',
        proposed:'proposed',
        leaderboard:'leaderboard',
        managegame:'manage',
        players:'members',
        newgame:'newgame', 
        details:'details/:id',    
    },
    home:{
        base:'home',
        login:'login',
        signup:'signup',
        cta:'cta',
    }
}